version: 2

models:
  # Staging models
  - name: stg_users
    description: Cleaned and standardized customer data
    columns:
      - name: user_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_products
    description: Cleaned product data with price in dollars
    columns:
      - name: product_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Completed orders only (excludes active carts)
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_order_items
    description: Cleaned order line items with price in dollars
    columns:
      - name: order_item_id
        description: Primary key
        tests:
          - unique
          - not_null

  # Mart models
  - name: fct_order_items
    description: Fact table with enriched order item data including customer and product details
    columns:
      - name: order_item_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: line_total_dollars
        description: Total value of this line item (unit_price * quantity)

  - name: mart_sales_summary
    description: Aggregated KPIs for dashboard scorecards (single row summary)
    columns:
      - name: total_revenue_dollars
        description: Sum of all completed order revenue
      - name: aov_dollars
        description: Average Order Value

  - name: mart_products
    description: Product performance metrics for top sellers and category analysis
    columns:
      - name: product_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: revenue_dollars
        description: Total revenue generated by this product

  - name: mart_customers
    description: Customer leaderboard with lifetime value metrics
    columns:
      - name: user_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: lifetime_value_dollars
        description: Total revenue from this customer

  - name: mart_sales_by_country
    description: Geographic sales breakdown for map visualization
    columns:
      - name: country
        description: Country name (primary key)
        tests:
          - unique
          - not_null
      - name: revenue_dollars
        description: Total revenue from this country
